from .user import User
from .pelicula import Pelicula
from .sala import Sala
from .funcion import Funcion
from .asiento_reservado import AsientoReservado
from .producto import Producto
from .reserva import Reserva
from .detalle_reserva import DetalleReserva
from .promocion import Promocion
from .venta import Venta
from .factura import Factura
