"""Corregir clave foránea en tabla reservas

Revision ID: 04b417fe1264
Revises: 23ec8b6d5325
Create Date: 2025-06-10 16:24:31.523225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04b417fe1264'
down_revision: Union[str, None] = '23ec8b6d5325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('funcion_id', sa.Integer(), nullable=False))
    op.add_column('reservas', sa.Column('asiento_reservado', sa.String(), nullable=False))
    op.add_column('reservas', sa.Column('fecha_reserva', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'reservas', 'funciones', ['funcion_id'], ['id'])
    op.drop_column('reservas', 'fecha_hora')
    op.drop_column('reservas', 'qr')
    op.drop_column('reservas', 'total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('reservas', sa.Column('qr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reservas', sa.Column('fecha_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reservas', type_='foreignkey')
    op.drop_column('reservas', 'fecha_reserva')
    op.drop_column('reservas', 'asiento_reservado')
    op.drop_column('reservas', 'funcion_id')
    # ### end Alembic commands ###
