"""crear tabla peliculas

Revision ID: 12dc25bc312a
Revises: 91369e0eede6
Create Date: 2025-06-06 20:17:44.893681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12dc25bc312a'
down_revision: Union[str, None] = '91369e0eede6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('idioma', sa.String(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('clasificacion', sa.String(), nullable=False),
    sa.Column('sinopsis', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('trailer_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peliculas_id'), 'peliculas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peliculas_id'), table_name='peliculas')
    op.drop_table('peliculas')
    # ### end Alembic commands ###
