"""Agregar tabla de asientos reservados

Revision ID: 23ec8b6d5325
Revises: 28ca7e74c68f
Create Date: 2025-06-10 16:13:15.373186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ec8b6d5325'
down_revision: Union[str, None] = '28ca7e74c68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asientos_reservados', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asientos_reservados', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
