"""Agregar columna descripcion a promociones

Revision ID: 28ca7e74c68f
Revises: 16a280ae9142
Create Date: 2025-06-10 15:59:59.168635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ca7e74c68f'
down_revision: Union[str, None] = '16a280ae9142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promociones', sa.Column('descripcion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promociones', 'descripcion')
    # ### end Alembic commands ###
