"""crear tablas del sistema

Revision ID: 7f641c8227a1
Revises: 12dc25bc312a
Create Date: 2025-06-06 20:27:25.017969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f641c8227a1'
down_revision: Union[str, None] = '12dc25bc312a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('tamaño', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('promociones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_promociones_id'), 'promociones', ['id'], unique=False)
    op.create_table('salas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('zona_precio', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salas_id'), 'salas', ['id'], unique=False)
    op.create_table('funciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pelicula_id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['pelicula_id'], ['peliculas.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funciones_id'), 'funciones', ['id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('qr', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_table('asientos_reservados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcion_id', sa.Integer(), nullable=False),
    sa.Column('asiento', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['funcion_id'], ['funciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asientos_reservados_id'), 'asientos_reservados', ['id'], unique=False)
    op.create_table('detalles_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_reserva_id'), 'detalles_reserva', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_reserva_id'), table_name='detalles_reserva')
    op.drop_table('detalles_reserva')
    op.drop_index(op.f('ix_asientos_reservados_id'), table_name='asientos_reservados')
    op.drop_table('asientos_reservados')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_funciones_id'), table_name='funciones')
    op.drop_table('funciones')
    op.drop_index(op.f('ix_salas_id'), table_name='salas')
    op.drop_table('salas')
    op.drop_index(op.f('ix_promociones_id'), table_name='promociones')
    op.drop_table('promociones')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
