"""Crear tabla de ventas

Revision ID: d29e1cfae23b
Revises: daf69fcd0039
Create Date: 2025-06-10 16:42:34.073158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29e1cfae23b'
down_revision: Union[str, None] = 'daf69fcd0039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'tamaño',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'tamaño',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
